### ISSUE TITLE
Can't select any WebID

### ISSUE THREAD

**Issue by nbaksalyar** [joshuef/eat#1]
1. I have created a new WebID, with a blank website field.
2. I have tried to search for it on `localhost:2345`.
3. I see no results appear.
4. There's an error reported in the console (file `Header.jsx:19`):
```
WebID entered not found: TypeError: Cannot read property 'object' of undefined
    at _callee5$ (http://localhost:2345/src.15cda922.js:38332:43)
    at tryCatch (http://localhost:2345/src.15cda922.js:31668:40)
    at Generator.invoke [as _invoke] (http://localhost:2345/src.15cda922.js:31902:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:2345/src.15cda922.js:31720:21)
    at step (http://localhost:2345/src.15cda922.js:38076:191)
    at http://localhost:2345/src.15cda922.js:38076:361
    at <anonymous>
```

**Comment by bochaco** [comment]
Thanks @nbaksalyar !
